// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: any/v1/any.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on OperationRecord with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *OperationRecord) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OperationRecord with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OperationRecordMultiError, or nil if none found.
func (m *OperationRecord) ValidateAll() error {
	return m.validate(true)
}

func (m *OperationRecord) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uid

	// no validation rules for Ip

	// no validation rules for Method

	// no validation rules for Path

	// no validation rules for Agent

	// no validation rules for Status

	// no validation rules for Latency

	// no validation rules for ReqBody

	// no validation rules for RespBody

	// no validation rules for DateTime

	// no validation rules for TraceID

	if len(errors) > 0 {
		return OperationRecordMultiError(errors)
	}

	return nil
}

// OperationRecordMultiError is an error wrapping multiple validation errors
// returned by OperationRecord.ValidateAll() if the designated constraints
// aren't met.
type OperationRecordMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OperationRecordMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OperationRecordMultiError) AllErrors() []error { return m }

// OperationRecordValidationError is the validation error returned by
// OperationRecord.Validate if the designated constraints aren't met.
type OperationRecordValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OperationRecordValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OperationRecordValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OperationRecordValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OperationRecordValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OperationRecordValidationError) ErrorName() string { return "OperationRecordValidationError" }

// Error satisfies the builtin error interface
func (e OperationRecordValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOperationRecord.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OperationRecordValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OperationRecordValidationError{}
