// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDebugPerf = "debug_perf"

// DebugPerf mapped from table <debug_perf>
type DebugPerf struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID        string         `gorm:"column:uid;not null;comment:uid" json:"uid"`
	Username   string         `gorm:"column:username;not null;comment:用户名" json:"username"`
	Motto      string         `gorm:"column:motto;not null;comment:座右铭" json:"motto"`
	Text       string         `gorm:"column:text;not null;comment:内容" json:"text"`
	CreateAt   time.Time      `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP;comment:记录创建时间" json:"create_at"`
	UpdateAt   time.Time      `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP;comment:记录修改时间" json:"update_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreateUser string         `gorm:"column:create_user;not null;comment:创建人" json:"create_user"`
	UpdateUser string         `gorm:"column:update_user;not null;comment:修改人" json:"update_user"`
}

// TableName DebugPerf's table name
func (*DebugPerf) TableName() string {
	return TableNameDebugPerf
}
