// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDebugPerf = "debug_perf"

// DebugPerf mapped from table <debug_perf>
type DebugPerf struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID        string         `gorm:"column:uid;not null" json:"uid"`                                           // uid
	Username   string         `gorm:"column:username;not null" json:"username"`                                 // 用户名
	Motto      string         `gorm:"column:motto;not null" json:"motto"`                                       // 座右铭
	Text       string         `gorm:"column:text;not null" json:"text"`                                         // 内容
	CreateTime time.Time      `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 记录创建时间
	UpdateTime time.Time      `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 记录修改时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreateUser string         `gorm:"column:create_user;not null" json:"create_user"` // 创建人
	UpdateUser string         `gorm:"column:update_user;not null" json:"update_user"` // 修改人
}

// TableName DebugPerf's table name
func (*DebugPerf) TableName() string {
	return TableNameDebugPerf
}
