// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMenu = "menu"

// Menu mapped from table <menu>
type Menu struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Path        string         `gorm:"column:path;not null;comment:路由" json:"path"`
	Name        string         `gorm:"column:name;not null;comment:名称" json:"name"`
	Redirect    string         `gorm:"column:redirect;not null;comment:重定向" json:"redirect"`
	Component   string         `gorm:"column:component;not null;comment:文件地址" json:"component"`
	ParentID    int32          `gorm:"column:parent_id;not null;comment:父id" json:"parent_id"`
	RoleIDGroup string         `gorm:"column:role_id_group;not null;comment:角色组" json:"role_id_group"`
	Title       string         `gorm:"column:title;not null;comment:标题" json:"title"`
	Icon        string         `gorm:"column:icon;not null;comment:图标" json:"icon"`
	Hidden      bool           `gorm:"column:hidden;not null;comment:是否隐藏" json:"hidden"`
	KeepAlive   bool           `gorm:"column:keep_alive;not null;default:1;comment:keepAlive" json:"keep_alive"`
	Sort        int32          `gorm:"column:sort;not null;comment:排序" json:"sort"`
	CreateAt    time.Time      `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP;comment:记录创建时间" json:"create_at"`
	UpdateAt    time.Time      `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP;comment:记录修改时间" json:"update_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreateUser  string         `gorm:"column:create_user;not null;comment:创建人" json:"create_user"`
	UpdateUser  string         `gorm:"column:update_user;not null;comment:修改人" json:"update_user"`
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
