// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSetting = "setting"

// Setting mapped from table <setting>
type Setting struct {
	ID                    int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID                   string         `gorm:"column:uid;not null" json:"uid"`                                         // uid
	Lang                  string         `gorm:"column:lang;not null" json:"lang"`                                       // 语言
	SideModeColor         string         `gorm:"column:side_mode_color;not null" json:"side_mode_color"`                 // 侧边栏颜色
	Collapse              bool           `gorm:"column:collapse;not null" json:"collapse"`                               // 侧边栏折叠
	Breadcrumb            bool           `gorm:"column:breadcrumb;not null;default:1" json:"breadcrumb"`                 // 面包屑
	DefaultRouter         string         `gorm:"column:default_router;not null" json:"default_router"`                   // 默认路由
	ActiveTextColor       string         `gorm:"column:active_text_color;not null" json:"active_text_color"`             // 活跃文本颜色
	ActiveBackgroundColor string         `gorm:"column:active_background_color;not null" json:"active_background_color"` // 活跃文本背景色
	CreateAt              time.Time      `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`   // 记录创建时间
	UpdateAt              time.Time      `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"`   // 记录修改时间
	DeletedAt             gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 删除时间
	CreateUser            string         `gorm:"column:create_user;not null" json:"create_user"`                         // 创建人
	UpdateUser            string         `gorm:"column:update_user;not null" json:"update_user"`                         // 修改人
}

// TableName Setting's table name
func (*Setting) TableName() string {
	return TableNameSetting
}
